Name: InfComs
Main: /DuncanA/InfComs/InfComs.php
Aurthor: DuncanA
Version: 1.0
API: 1.12.0
Description: Adds commands with information and action into the PocketMine-MP Server Software for Minecraft Pocket Edition.

commands:
 info:
  description: "Shows information about the server"
  usage: "/info <status|ip|player|op>
  permission: myplugin.example
  quit:
  description: "Kicks player from server"
  usage: "/quit [secondstilkick]
  permission: player.kick
  inv:
  description: "Lists items in Player Iv"
  usage: "/inv <showall|showarmor|showitems>
  permission: inventory.BaseInventory
